### ISSUE TITLE
Use all_after_pass: true only for certain specs?

### ISSUE THREAD

**Issue by jmuheim** [guard/guard-rspec#239]
I find `all_after_pass: true` a very useful option, but in a large project it simply takes too much time (for example when having acceptance/request specs).

It would be nice to have an option to limit this option somehow, e.g. that only the tests in the specific file that was saved are rerun, or only the tests in the same folder (and maybe even subfolders).

**Comment by e2** [comment]
I'm closing this, because I think the whole "all_after_pass" can be replaced with 2 (or more) `:rspec` guards running RSpec with different tags, and the `:halt_on_failure` group option, e.g. like here:

http://stackoverflow.com/questions/21073910/how-to-get-guard-to-only-run-slow-specs-if-fast-specs-pass/27525210#27525210

Instead of supporting actions after successes, Guard::RSpec should rather focus on responding to failures (which is something Guard can't handle).
