### ISSUE TITLE
spec_paths autoloads child folders

### ISSUE THREAD

**Issue by auzroz** [guard/guard-rspec#274]
Currently working on a project that has two sets or specs, one for locally hosted data using webmock and the other that uses remote data from the source.

The folder structure is currently such that the remote specs are a directory under the main directory where the local specs are held. 
```
specs
|-flightstats
|--remote
```

When I try to setup guard-rspec to only run the local specs, it autoloads the remote specs anyways.

```
guard 'rspec', :spec_paths => ['spec/flightstats'] do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^spec/flightstats/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^lib/flightstats/(.+)\.rb$})     { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^lib/flightstats/api/(.+)\.rb$})     { |m| "spec/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }
end
```

If I use the following code, it ignores the remote specs, but doesn't run the specs when a file change is detected.
```
guard 'rspec', :spec_paths => ['spec/flightstats/*_spec.rb'] do
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^spec/flightstats/.+_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})     { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^lib/flightstats/(.+)\.rb$})     { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^lib/flightstats/api/(.+)\.rb$})     { |m| "spec/#{m[1]}_spec.rb" }
  watch('spec/spec_helper.rb')  { "spec" }
end
```

A workaround for the time being is to move the remote directory out of the flightstats directory.

**Comment by e2** [comment]
If I understand correctly, a better solution would be to tag remote tests - and instead have 2 `:rspec` guards - one to run the non-remote tests, and another to run the remote tests afterwards (if the non-remote ones succeed).

What I don't understand is: how the source files are related to the remote files. The question is: why do you want to ignore the remote specs? If it's because you want to skip them, you can use RSpec metadata and pass a '-t' option. If you want to run them "after everything else works" - you'll want to run tests twice (one with e.g `-t ~remote` and then `-t remote`) using two guards (mentioned above).

If this is still relevant, please reopen and give me a specific example of:
- which source file you change, and which tests you want running and which you want to skip (and why)

Selecting files is quite complex in Guard::RSpec, so it's best to have a clear example of a bug (to avoid breaking other stuff).
