### ISSUE TITLE
ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!

### ISSUE THREAD

**Issue by dchersey** [guard/guard-rspec#313]
D, [2015-01-27T14:27:59.040844 #79621] DEBUG -- : Terminating 4 actors...
E, [2015-01-27T14:28:09.042073 #79621] ERROR -- : Couldn't cleanly terminate all actors in 10 seconds!

I keep getting this error after running my specs with guard -- I have googled a bit and it seems to also pop up with other gems (https://github.com/mperham/sidekiq/issues/1268, https://github.com/brandonhilkert/sucker_punch/issues/43, https://github.com/RiotGames/ridley/issues/220) and even with omega-guard (https://www.drupal.org/node/2392375)

Seeing this diversity, I expect this is due to something underlying all of these that guard also makes use of, that I need to update.  It is not happening with a newly generated rails 4.2 app I have, for which I have installed fresh gems.

I deleted my Gemfile.lock, did a bundle update with no effect.

when I run bundle exec rspec by itself, it works fine
D, [2015-01-27T14:35:16.819471 #79671] DEBUG -- : Terminating 4 actors...

Any thoughts?

**Comment by e2** [comment]
First, check you're using the latest Celluloid on those projects (0.16.0 I guess).

If you are using spring, make sure you have the latest version too.

Next - try commenting out specific plugins in the Guardfile until the issue stops.

A known cause is some gem calling fork() while another is using `Listen` (like `Guard`) which uses `Celluloid`.

Basically, Celluloid uses threads. Calling fork() creates a copy of the process, but doesn't copy threads. This leads to a cloned memory copy of Celluloid - but one without all the threads dead. 

Afterwards, Celluloid tries to kill the (dead) threads, and gives them 10 seconds to respond.

If you just want to reduce the timeout, just put the following somewhere on startup:
```ruby
Celluloid.shutdown_timeout = 1 # or 0.5 or whatever is "safe" for your project
```

If you find some guard plugins are in conflict because of this, it's best to run whatever calls fork() separately.

So the output may actually be harmless. I'm closing this because of: https://github.com/celluloid/celluloid/issues/468

Hope that helps.

**Comment by copremesis** [comment]
removing spring is what fixed it for me ... YAGNI

**Comment by e2** [comment]
FWIW, Listen 3.x doesn't rely on Celluloid anymore - so just upgrading to Listen 3.x should solve this.
