### ISSUE TITLE
exclude path from sub-directory

### ISSUE THREAD

**Issue by ITler** [guard/guard-rspec#342]
Inspired from your README, I use guard-rspec to watch my puppet module spec files:

    1 guard 'rspec', :cmd => "bundle exec rspec", :cmd_additional_args => "-f p -c" do
    2   watch(%r{^spec/.+_spec\.rb$})
    3   watch(%r{^manifests/(.+)\.pp$})  { |m| "spec/classes/#{m[1]}_spec.rb" }
    4   watch('spec/spec_helper.rb')  { "spec" }
    5 end

If line 4 watch is triggered, guard will do an `all rspec`, which will trigger tests included in 3rd party module sources. These are placed within `spec/fixtures/modules/` by default.

Unfortunately, there are errors raised, when those 3rd party modules are tested with guard-rspec (my rake spec is doing fine). How could I exclude that path `spec/fixtures/modules/`, as I don't want to execute test of 3rd party sources? 
I know, that there is a RSpec::configure::exclude_pattern but how to feed it from guard-rspec?

**Comment by e2** [comment]
There used to be an `:exclude` option in Guard::RSpec, but this was removed in favor of just ignoring files by Guard.

I think you have 2 options here:

1. add the rspec option on the command line, using RSpec's `--exclude-pattern` option in the `:cmd_additional_args` parameter
2. explicitly list all the specs instead as an array instead of `"spec"` - I believe returning an array in the block should work, so you can do e.g. 
```ruby
watch('spec/spec_helper.rb') { Dir['spec/**/*_spec.rb'] }
```

**Comment by ITler** [comment]
Option 1 seems to work. Hopefully `--exclude-pattern` won't be removed ;) 

Thanks so far.

**Comment by ITler** [comment]
Thanks
