### ISSUE TITLE
Rails 5 support for rspec-rails

### ISSUE THREAD

**Issue by bsodmike** [guard/guard-rspec#365]
Issues in the rspec-rails project provide instructions to use the master branch, which currently has a version `3.5.0.beta3`; this complicates matters as this is a pre-release version.

Therefore, for the time being I've [made changes to the gemspec to reflect this](https://github.com/bsodmike/guard-rspec/commit/299561df951fe1d86275f19c4ffb6953e0ef7bc3).  Would be great if one of the project maintainers could cherry-pick my changes in to a new `rails-5-support` branch.

This works in [tandem with my patch for `rspec-rails` for Rails 5](https://github.com/rspec/rspec-rails/pull/1601).

**Comment by e2** [comment]
Cool!

You can just submit pull requests to the branch: https://github.com/guard/guard-rspec/tree/rails-5-support.

Since guard-rspec pretty much doesn't care about the RSpec version, it should be up to rspec-rails to pessimistically lock ~> 3.5 once it's released.

guard-rspec could be updated to pessimistically lock to some RSpec 3.x version, but until now there simply hasn't been a reason to. (2.99 RSpec version happens to be supported - there's little reason for it).

**Comment by bsodmike** [comment]
Thanks @e2, appreciate the assistance.

> it should be up to rspec-rails to pessimistically lock ~> 3.5 once it's released

Agreed!
